=begin
#Merchandice Product API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PatchOperation
    ADD = "add".freeze
    REMOVE = "remove".freeze
    REPLACE = "replace".freeze
    MOVE = "move".freeze
    COPY = "copy".freeze
    TEST = "test".freeze

    def self.all_vars
      @all_vars ||= [ADD, REMOVE, REPLACE, MOVE, COPY, TEST].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PatchOperation.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PatchOperation"
    end
  end
end
