=begin
#Merchandice Product API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PatchOperation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PatchOperation do
  let(:instance) { OpenapiClient::PatchOperation.new }

  describe 'test an instance of PatchOperation' do
    it 'should create an instance of PatchOperation' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PatchOperation)
    end
  end

end
