=begin
#Merchandice Product API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

# Common files
require 'merchandice_product_sdk/api_client'
require 'merchandice_product_sdk/api_error'
require 'merchandice_product_sdk/version'
require 'merchandice_product_sdk/configuration'

# Models
require 'merchandice_product_sdk/models/api_products_id_patch_request'
require 'merchandice_product_sdk/models/json_patch_inner'
require 'merchandice_product_sdk/models/patch_operation'
require 'merchandice_product_sdk/models/product'
require 'merchandice_product_sdk/models/product_attribute'
require 'merchandice_product_sdk/models/product_price'
require 'merchandice_product_sdk/models/product_rating'
require 'merchandice_product_sdk/models/product_response'
require 'merchandice_product_sdk/models/product_variation'

# APIs
require 'merchandice_product_sdk/api/products_api'

module MerchandiceProductSdk
  class << self
    # Customize default settings for the SDK using block.
    #   MerchandiceProductSdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
